openapi: 3.0.0
info:
  title: OpenAPI 3.0 example
  version: 0.0.1
  description: An example API
servers: 
  - url: https://api.example.com/
paths:
  /things:
    get:
      description: Get some things
      summary: get
      tags:
        - Get
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/things'
    post:
      requestBody:
        description: Thing
        required: true
        content: 
          application/json:
            schema:
              $ref: '#components/schemas/thing'
      description: Create a new thing
      summary: post
      tags:
        - Post
      responses:
        201:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/thing'
components:
  schemas:
    thing:
      $ref: schemas/definitions.yaml#/thing
    things:
      items:
        $ref: '#/components/schemas/thing'